### ISSUE TITLE
Quickstart broken with newest conda

### ISSUE THREAD

**Issue by mdagost** [ucbrise/clipper#269]
It looks like there's a problem with the Quickstart instructions [here](http://clipper.ai/overview/quickstart/).  It's during the anaconda environment bundling:

```
AttributeError: 'ResolvePackageNotFound' object has no attribute 'pkgs'
```

Here are my versions of python and conda:

```
(clipper) [ mdagostino: ~ ]$ python --version
Python 2.7.10 :: Continuum Analytics, Inc.
(clipper) [ mdagostino: ~ ]$ conda --version
conda 4.3.24
```

I think the problem is that there were recent changes to `ResolvePackageNotFound`:

https://github.com/conda/conda/blob/master/conda/exceptions.py#L31-L36

Here's the full output:

```
In [1]: from clipper_admin import Clipper

In [2]: clipper_conn = Clipper("localhost")
Checking if Docker is running...

In [3]: clipper_conn.start()
Note: Docker must download the Clipper Docker images if they are not already cached. This may take awhile.
Clipper is running

In [4]: clipper_conn.register_application("hello_world", "feature_sum_model", "doubles", "-1.0", 100000)
Success!
Out[4]: True

In [5]: clipper_conn.get_all_apps()
Out[5]: [u'hello_world']

In [6]: def pred(xs):
   ...:       return [str(np.sum(x)) for x in xs]
   ...: 

In [7]: clipper_conn.deploy_predict_function("feature_sum_model", 1, pred, "doubles")
Anaconda environment found. Verifying packages.

Traceback (most recent call last):
  File "/Users/mdagostino/miniconda2/envs/clipper/lib/python2.7/site-packages/clipper_admin/check_and_write_deps.py", line 125, in <module>
    conda_dep_fname, pip_dep_fname):
  File "/Users/mdagostino/miniconda2/envs/clipper/lib/python2.7/site-packages/clipper_admin/check_and_write_deps.py", line 90, in check_solvability_write_deps
    missing_packages = missing_packages_error.pkgs
AttributeError: 'ResolvePackageNotFound' object has no attribute 'pkgs'

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-12be21fbcd77> in <module>()
----> 1 clipper_conn.deploy_predict_function("feature_sum_model", 1, pred, "doubles")

/Users/mdagostino/miniconda2/envs/clipper/lib/python2.7/site-packages/clipper_admin/clipper_manager.pyc in deploy_predict_function(self, name, version, predict_function, input_type, labels, num_containers)
    742                                           labels, num_containers)
    743         # Remove temp files
--> 744         shutil.rmtree(serialization_dir)
    745 
    746         return deploy_result

/Users/mdagostino/miniconda2/envs/clipper/lib/python2.7/shutil.pyc in rmtree(path, ignore_errors, onerror)
    226             raise
    227     try:
--> 228         if os.path.islink(path):
    229             # symlinks to directories are forbidden, see bug #1669
    230             raise OSError("Cannot call rmtree on a symbolic link")

/Users/mdagostino/miniconda2/envs/clipper/lib/python2.7/posixpath.pyc in islink(path)
    133     """Test whether a path is a symbolic link"""
    134     try:
--> 135         st = os.lstat(path)
    136     except (os.error, AttributeError):
    137         return False

TypeError: coercing to Unicode: need string or buffer, bool found
```

**Comment by dcrankshaw** [comment]
Thanks for bringing this to our attention (and for digging into the cause!). We'll look into this ASAP.

**Comment by mdagost** [comment]
Thanks!  A bit more info.  I rolled back to conda `4.3.21`, and I don't get that error anymore.  It becomes

```
The following packages in your conda environment aren't available in the linux-64 conda channel the container will use:
appnope 0.1.0 py27_0
We will skip their installation when deploying your function. If your function uses these packages, the container will experience a runtime error when queried.
```

However, now it fails with

```
Supplied environment details
Serialized and supplied predict function
model_data_path is: /tmp/predict_serializations/feature_sum_model
Published model to Clipper
Found clipper/python-container on host
Copied model data to host

Fatal error: local() encountered an error (return code 127) while executing 'redis-cli -h localhost -p 6379 -n 2 hgetall feature_sum_model:1'

================================================= Standard error =================================================

/bin/sh: redis-cli: command not found

===================================================================================================================

Aborting.
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1

/Users/mdagostino/miniconda2/envs/clipper/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2889: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
```

Do I need to have local redis installed?  Didn't see that in the Quickstart.

**Comment by mdagost** [comment]
For posterity, for anyone who comes after me, I had to do 2 things to get the Quickstart instructions to work.  I had to `brew install redis` on a Mac to get a local `redis-cli`, and I had to change the imports to

```
from clipper_admin import Clipper
import numpy as np
```
