### ISSUE TITLE
sklearn model not able to find cifar10 data

### ISSUE THREAD

**Issue by abuvaneswari** [ucbrise/clipper#291]
Hello,

I am trying to run your performance benchmark code with your sklearn model (https://github.com/ucbrise/clipper/blob/develop/bench/setup_sklearn_bench.sh)

============================================================
First, I downloaded the cifar10 dataset using your python download scirpt (https://github.com/ucbrise/clipper/blob/develop/examples/tutorial/download_cifar.py) to a local directory. 

$ ls
batches.meta	  data_batch_1	data_batch_3  data_batch_5  test_batch
cifar_train.data  data_batch_2	data_batch_4  readme.html

===========================================================
Tried to run setup_sklearn_bench.sh as below. It seems to be looking for cifar_train.data, which does not exist in the bundle. Are there other CIFAR10 related preprocessing steps that are left out in your instructions?

$ ./bench/setup_sklearn_bench.sh ~/clipper/cifar10/cifar-10-batches-py/

Loading Sklearn Model...

Loading CIFAR data...
Traceback (most recent call last):
  File "bench/bench_init.py", line 77, in <module>
    setup.run()
  File "bench/bench_init.py", line 34, in run
    self.train_sklearn_model()
  File "bench/bench_init.py", line 60, in train_sklearn_model
    test_x, test_y, train_x, train_y = self.get_cifar_data()
  File "bench/bench_init.py", line 39, in get_cifar_data
    norm=False))
  File "/home/XXXX/clipper/clipper/examples/tutorial/cifar_utils.py", line 56, in load_cifar
    df = pd.read_csv(cifar_path, sep=",", header=None)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 405, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 762, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 966, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/parsers.py", line 1582, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 394, in pandas._libs.parsers.TextReader.__cinit__ (pandas/_libs/parsers.c:4209)
  File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source (pandas/_libs/parsers.c:8873)
IOError: File /home/XXXX/clipper/cifar10/cifar-10-batches-py/cifar_train.data does not exist

plmk a solution.

thanks,
Buvana

**Comment by dcrankshaw** [comment]
Ahh yes there is a step missing from the instructions in `bench/README.md`. After you download the Python CIFAR dataset, you need to extract the data to a CSV. From the root of the Clipper directory, run:

```
python examples/tutorial/extract_cifar.py <path_to_downloaded_dataset> <num_train_datapoints> <num_test_datapoints>
```

To be extra clear, `<path_to_downloaded_dataset>` should be the exact same argument you provided to the download script. The `extrac_cifar.py` script will automatically look for the data in `<path_to_downloaded_dataset>/cifar-10-batches-py`. 

Finally, you can run `./bench/setup_sklearn_bench.sh` with the same path. So in your case, the following code should work:

```
python examples/tutorial/download_cifar.py ~/clipper/cifar10
python examples/tutorial/extract_cifar.py ~/clipper/cifar10 10000 10000
./bench/setup_sklearn_bench.sh ~/clipper/cifar10
```

I will update the README to fix this.
