### ISSUE TITLE
Error when running integration tests

### ISSUE THREAD

**Issue by ryanhoque** [ucbrise/clipper#379]
After passing about 10 of the integration tests, all subsequent tests fail with the exact same "Too many open files" error in what seems to be the requests module. Issue has been experienced by myself and another developer independently with a clean copy of the code. Stack trace is as follows:

```
Traceback (most recent call last):
  File "../integration-tests/clipper_admin_tests.py", line 49, in setUp
  File "/Users/ryanhoque/Documents/Github/ucbrise/clipper/integration-tests/test_utils.py", line 72, in create_docker_connection
  File "/Users/ryanhoque/Documents/Github/ucbrise/clipper/clipper_admin/clipper_admin/clipper_admin.py", line 1188, in stop_all
  File "/Users/ryanhoque/Documents/Github/ucbrise/clipper/clipper_admin/clipper_admin/docker/docker_container_manager.py", line 300, in stop_all
  File "/Users/ryanhoque/Documents/Dev/python-env/lib/python2.7/site-packages/docker/models/containers.py", line 368, in stop
  File "/Users/ryanhoque/Documents/Dev/python-env/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "/Users/ryanhoque/Documents/Dev/python-env/lib/python2.7/site-packages/docker/api/container.py", line 1139, in stop
  File "/Users/ryanhoque/Documents/Dev/python-env/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
  File "/Users/ryanhoque/Documents/Dev/python-env/lib/python2.7/site-packages/docker/api/client.py", line 187, in _post
  File "/Users/ryanhoque/Documents/Dev/python-env/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
  File "/Users/ryanhoque/Documents/Dev/python-env/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
  File "/Users/ryanhoque/Documents/Dev/python-env/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
  File "/Users/ryanhoque/Documents/Dev/python-env/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
ConnectionError: ('Connection aborted.', error(24, 'Too many open files'))
```

**Comment by simon-mo** [comment]
The issue is your file descriptor limit too low. 
1. Run `ulimit -a` to see how many file descriptor allowed in your current system. 
2. Adjust the limit according to https://github.com/elastic/elasticsearch/issues/18022

**Comment by simon-mo** [comment]
And you should probably just run the integration test for the specific function your are working on. And then leave the full integration test for jenkins to run.

**Comment by ryanhoque** [comment]
Makes sense. Thanks Simon!
