### ISSUE TITLE
requests.exceptions.ChunkedEncodingError is occurred in check_and_write_deps.py

### ISSUE THREAD

**Issue by withsmilo** [ucbrise/clipper#381]
This error is occurred very rarely. I think that we might add some retries to `check_solvability_write_deps` function.
```
2018-01-29 00:06:35,295 INFO     [clipper_manager.py:36] Start to deploy the model
2018-01-29 00:06:35,535 INFO     [deployer_utils.py:49] Saving function to /tmp/clipper/tmpMhfp8u
2018-01-29 00:06:37,480 INFO     [deployer_utils.py:58] Anaconda environment found. Verifying packages.
2018-01-29 00:06:39,836 INFO     [deployer_utils.py:158]
2018-01-29 00:06:39,836 INFO     [deployer_utils.py:159] Traceback (most recent call last):
  File "/home1/user1/anaconda2/envs/py27/lib/python2.7/site-packages/clipper_admin/deployers/check_and_write_deps.py", line 127, in <module>
    conda_dep_fname, pip_dep_fname):
  File "/home1/user1/anaconda2/envs/py27/lib/python2.7/site-packages/clipper_admin/deployers/check_and_write_deps.py", line 69, in check_solvability_write_deps
    index = get_index(platform=platform)
  File "/home1/user1/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 101, in get_index
    index = fetch_index(channel_priority_map, use_cache=use_cache)
  File "/home1/user1/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 120, in fetch_index
    repodatas = collect_all_repodata(use_cache, tasks)
  File "/home1/user1/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
    repodatas = _collect_repodatas_serial(use_cache, tasks)
  File "/home1/user1/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
    for url, schan, pri in tasks]
  File "/home1/user1/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 115, in func
    res = f(*args, **kwargs)
  File "/home1/user1/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 464, in fetch_repodata
    mod_etag_headers.get('_mod'))
  File "/home1/user1/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 144, in fetch_repodata_remote_request
    timeout=timeout)
  File "/home1/user1/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/home1/user1/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home1/user1/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 658, in send
    r.content
  File "/home1/user1/anaconda2/lib/python2.7/site-packages/requests/models.py", line 823, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/home1/user1/anaconda2/lib/python2.7/site-packages/requests/models.py", line 748, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: error("(104, \'ECONNRESET\')",)', error("(104, 'ECONNRESET')",))
```

**Comment by dcrankshaw** [comment]
Yeah that function is a little flaky. @withsmilo can you submit a PR with those checks?

**Comment by withsmilo** [comment]
@dcrankshaw OK. I will do it.
