### ISSUE TITLE
connection refused connecting with clipper at local host port 

### ISSUE THREAD

**Issue by dsimmen** [ucbrise/clipper#446]
Working through first install and "hello world".   Any ideas why this is failing. 

dsimmen-MBP-8C916:~ dsimmen$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from clipper_admin import ClipperConnection, DockerContainerManager
>>> clipper_conn = ClipperConnection(DockerContainerManager())
>>> clipper_conn.connect()
18-03-20:18:00:40 INFO     [clipper_admin.py:123] Successfully connected to Clipper cluster at localhost:1337
>>> clipper_conn.register_application(name="hello-world", input_type="doubles", default_output="-1.0", slo_micros=100000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dsimmen/Library/Python/2.7/lib/python/site-packages/clipper_admin/clipper_admin.py", line 177, in register_application
    r = requests.post(url, headers=headers, data=req_json)
  File "/Library/Python/2.7/site-packages/requests-2.18.4-py2.7.egg/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.18.4-py2.7.egg/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.18.4-py2.7.egg/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.18.4-py2.7.egg/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=1338): Max retries exceeded with url: /admin/add_app (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10d665f50>: Failed to establish a new connection: [Errno 61] Connection refused',))

**Comment by withsmilo** [comment]
@dsimmen 
Did you start Clipper before registering the 'hello-world' application?
```python
clipper_conn.start_clipper()
```

**Comment by dsimmen** [comment]
Thanks for reply. I sent the wrong session : ) Yes, there us a start_clipper() error. Thanks.

dsimmen-MBP-8C916:~ dsimmen$ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from clipper_admin import ClipperConnection, DockerContainerManager
>>> clipper_conn = ClipperConnection(DockerContainerManager())
>>> clipper_conn.start_clipper()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dsimmen/Library/Python/2.7/lib/python/site-packages/clipper_admin/clipper_admin.py", line 101, in start_clipper
    cache_size)
  File "/Users/dsimmen/Library/Python/2.7/lib/python/site-packages/clipper_admin/docker/docker_container_manager.py", line 90, in start_clipper
    self.docker_network, check_duplicate=True)
  File "/Library/Python/2.7/site-packages/docker/models/networks.py", line 154, in create
    resp = self.client.api.create_network(name, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/docker/api/network.py", line 150, in create_network
    url = self._url("/networks/create")
  File "/Library/Python/2.7/site-packages/docker/api/client.py", line 212, in _url
    quote_f = partial(six.moves.urllib.parse.quote, safe="/:")
AttributeError: 'Module_six_moves_urllib_parse' object has no attribute 'quote'
>>>

DS

**Comment by dcrankshaw** [comment]
Hi @dsimmen. Sorry you're having trouble. Let me see if I can help you debug.

What version of Python are you using? Were you able to successfully run `start_clipper()`? If so, can you paste the output of `docker ps -a` after you start Clipper?

**Comment by simon-mo** [comment]
The issue seems to be the MacOS pre installed package (six). Few comments
and solution here:
https://github.com/google/google-api-python-client/issues/100

**Comment by dsimmen** [comment]
Thanks for the pointer. I needed to upgrade osx six package. This command worked for me “pip install six --upgrade --user python”
