### ISSUE TITLE
Run quick start failed

### ISSUE THREAD

**Issue by aksnzhy** [ucbrise/clipper#521]
The Error:

```
>>> clipper_conn.start_clipper()
18-06-18:23:07:17 INFO     [docker_container_manager.py:119] Starting managed Redis instance in Docker
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/create?name=mgmt_frontend-87866

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/models/containers.py", line 766, in run
    detach=detach, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/models/containers.py", line 824, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/container.py", line 410, in create_container
    return self.create_container_from_config(config, name)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/container.py", line 421, in create_container_from_config
    return self._result(res, True)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/client.py", line 235, in _result
    self._raise_for_status(response)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: clipper/management_frontend:0.3.0")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/client.py", line 229, in _raise_for_status
    response.raise_for_status()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/images/clipper/management_frontend:0.3.0/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.5/site-packages/clipper_admin/clipper_admin.py", line 114, in start_clipper
    cache_size, num_frontend_replicas)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/clipper_admin/docker/docker_container_manager.py", line 144, in start_clipper
    **self.extra_container_kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/models/containers.py", line 768, in run
    self.client.images.pull(image, platform=platform)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/models/images.py", line 415, in pull
    repository, tag, '@' if tag.startswith('sha256:') else ':'
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/models/images.py", line 295, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/image.py", line 245, in inspect_image
    self._get(self._url("/images/{0}/json", image)), True
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/client.py", line 235, in _result
    self._raise_for_status(response)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("no such image: clipper/management_frontend:0.3.0: No such image: clipper/management_frontend:0.3.0")
```

**Comment by withsmilo** [comment]
@aksnzhy 
Please try to download `clipper/management_frontend:0.3.0` Docker image directly.
```
$ docker pull clipper/management_frontend:0.3.0
```
If failed, check your Docker registry.
```
$ docker info
...
Registry: https://index.docker.io/v1/
...
```
