### ISSUE TITLE
XGBoost Example: 

### ISSUE THREAD

**Issue by donigian** [ucbrise/clipper#541]
System information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS X
clipper installed from (source or binary): binary
clipper version (): master branch
Python version: Python 3.6.5 :: Anaconda, Inc.

The [XGBoost example ](http://clipper.ai/tutorials/xgboost_deployment/) returns:
```
{'query_id': 0,
 'output': 'default_pred',
 'default': True,
 'default_explanation': 'Failed to retrieve a prediction response within the specified latency SLO'}
```

According to [FAQ](http://clipper.ai/tutorials/troubleshooting/), `clipper_conn.inspect_instance()` returns:

```
{'counters': [{'internal:prediction_cache_lookups': {'count': '1'}},
  {'internal:aggregate_num_predictions': {'count': '1'}},
  {'app:xgboost-test:num_predictions': {'count': '1'}},
  {'model:xgboost-model:2:num_predictions': {'count': '0'}}],
 'ratio_counters': [{'internal:prediction_cache_hit_ratio': {'ratio': '0'}},
  {'app:xgboost-test:default_prediction_ratio': {'ratio': '1'}},
  {'model:xgboost-model:2:cache_hit_ratio': {'ratio': '0'}}],
 'meters': [{'internal:aggregate_model_throughput': {'unit': 'events per second',
    'rate': '0',
    'rate_1min': '0',
    'rate_5min': '0',
    'rate_15min': '0'}},
  {'app:xgboost-test:prediction_throughput': {'unit': 'events per second',
    'rate': '0.102398311820472',
    'rate_1min': '0',
    'rate_5min': '0',
    'rate_15min': '0'}},
  {'model:xgboost-model:2:prediction_throughput': {'unit': 'events per second',
    'rate': '0',
    'rate_1min': '-1',
    'rate_5min': '-1',
    'rate_15min': '-1'}}],
 'histograms': [{'internal:rpc_request_queueing_delay': {'unit': 'microseconds',
    'size': '1',
    'min': '17628',
    'max': '17628',
    'mean': '17628',
    'std_dev': '0',
    'p50': '17628',
    'p95': '17628',
    'p99': '17628'}},
  {'app:xgboost-test:prediction_latency': {'unit': 'microseconds',
    'size': '1',
    'min': '199148',
    'max': '199148',
    'mean': '199148',
    'std_dev': '0',
    'p50': '199148',
    'p95': '199148',
    'p99': '199148'}},
  {'model:xgboost-model:2:prediction_latency': {'unit': 'microseconds',
    'size': '0',
    'min': '0',
    'max': '0',
    'mean': '0',
    'std_dev': '0',
    'p50': '0',
    'p95': '0',
    'p99': '0'}},
  {'model:xgboost-model:2:batch_size': {'unit': 'queries',
    'size': '0',
    'min': '0',
    'max': '0',
    'mean': '0',
    'std_dev': '0',
    'p50': '0',
    'p95': '0',
    'p99': '0'}}]}
```

I set `clipper_conn.register_application('xgboost-test', 'integers', 'default_pred', 200000)` but still get the SLO error. Please advise.

**Comment by RehanSD** [comment]
Hi @donigian!
Would it be possible for you to post the output of the XGBoost model container logs here? The container missing the SLO could be because it is failing for another reason, and the logs can help me assess that.
Thanks!

**Comment by donigian** [comment]
@RehanSD 
Here are the only docker containers which are up? Do you know what the name of the XGBoost model container would be? It might be dead if you don't see it in the list below.

```
mbp ~ $ docker ps                                                                                                                                                                             [2.2.2]
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                                            NAMES
d5c8118e836d        prom/prometheus:v2.1.0                "/bin/prometheus --c…"   10 seconds ago      Up 17 seconds       0.0.0.0:9090->9090/tcp                           metric_frontend-91987
3c560365f5f8        clipper/frontend-exporter:develop     "python /usr/src/app…"   11 seconds ago      Up 17 seconds                                                        query_frontend_exporter-29528
0866aafa553f        clipper/query_frontend:develop        "/clipper/release/sr…"   12 seconds ago      Up 18 seconds       0.0.0.0:1337->1337/tcp, 0.0.0.0:7000->7000/tcp   query_frontend-29528
fbecfdf26082        clipper/management_frontend:develop   "/clipper/release/sr…"   13 seconds ago      Up 19 seconds       0.0.0.0:1338->1338/tcp                           mgmt_frontend-15406
086974a20c37        redis:alpine                          "docker-entrypoint.s…"   14 seconds ago      Up 20 seconds       0.0.0.0:6379->6379/tcp                           redis-78656
```

I suspect it may be `docker logs query_frontend-29528`, but the resulting file is 8xxx lines long!

**Comment by jayantjain93** [comment]
I am getting the exact same issue.
post the SLO exception I start requesting again and I get
`
b'{"query_id":16,"output":-1,"default":true,"default_explanation":"No connected models found for query"}'
`
The model dockers doesn't appear anymore in the docker list. Got the following message in the model docker logs
```
Traceback (most recent call last):
  File "/container/python_closure_container.py", line 61, in <module>
    rpc_service.start(model)
  File "/container/rpc.py", line 726, in start
    self.server.run(collect_metrics=self.collect_metrics)
  File "/container/rpc.py", line 353, in run
    prediction_request)
  File "/container/rpc.py", line 167, in handle_prediction_request
    (len(prediction_request.inputs), len(outputs)))
rpc.PredictionError: 'Expected model to return 2 outputs, found 1 outputs'
Encountered error not related to missing packages. Please refer to the container log to diagnose.
```
The 2 output error seems to be there even when I'm sending a single input batch.
Seems like if there is an exception the model exits.
Client code:
```
session = requests.session()
        while True:
            featureVector = []
            i = 0
            while i < 1:
                featureVectorTemp = []
                featureVectorTemp = next(vector)
                featureVector.append(featureVectorTemp)
                i += 1
            # start_time = time.time()
            # result = predict(featureVector)
            # end_time = time.time()
            # print(str((end_time - start_time) * 1000))
            # print(str(result))
            start_time = time.time()
            # print(featureVector)
            print(json.dumps({'input': featureVector[0]}))
            resp = session.post("http://localhost:1337/xgboost-test/predict", headers={"Content-type": "application/json"}, data=json.dumps({'input': featureVector[0]}))
            # print(resp.content)
            print("got response " + str(resp.content))
            print("got json " + str(resp.json()))
            prediction = resp.content
            end_time = time.time()
            diff_ms = (end_time - start_time) * 1000
            timers.append(diff_ms)
            predictions.extend(prediction)
            time.sleep(10)
```
where `print(json.dumps({'input': featureVector[0]}))` prints `{"input": [18411.0, 12.0, 1.0, 0.0, 12.0, 0.0, 0.0, 4.0, 6.0]}`

server code:
```
import xgboost as xgb
import pickle
from clipper_admin import ClipperConnection, DockerContainerManager
from clipper_admin.deployers import python as python_deployer

cl = ClipperConnection(DockerContainerManager())

ClipperConnection.start_clipper(cl)
print("connected the clipper admin")

cl.register_application('xgboost-test', 'floats', '-1', 100000)
print("application registered")

model_name = "./model.dat"
model = pickle.load(open(str(model_name),'rb'))

def predict(xs):
    return [model.predict(xgb.DMatrix(xs,label=None,feature_names=None))]

python_deployer.deploy_python_closure(cl, name='xgboost-model', version=1,
     input_type="floats", func=predict, pkgs_to_install=['xgboost==0.7.post3','pickleshare==0.7.4'])

cl.link_model_to_app('xgboost-test', 'xgboost-model')
```

**Comment by jayantjain93** [comment]
If I got ahead and change the predict function to that given in the example:
```def predict(xs):
    return [str(model.predict(xgb.DMatrix(x,label=None,feature_names=None))) for x in xs ]
```

I get the following error:
```
Traceback (most recent call last):
  File "/container/python_closure_container.py", line 61, in <module>
    rpc_service.start(model)
  File "/container/rpc.py", line 726, in start
    self.server.run(collect_metrics=self.collect_metrics)
  File "/container/rpc.py", line 353, in run
    prediction_request)
  File "/container/rpc.py", line 160, in handle_prediction_request
    outputs = predict_fn(prediction_request.inputs)
  File "/container/python_closure_container.py", line 35, in predict_floats
    preds = self.predict_func(inputs)
  File "server.py", line 18, in predict
  File "/usr/local/lib/python2.7/site-packages/xgboost/core.py", line 280, in __init__
    self._init_from_npy2d(data, missing, nthread)
  File "/usr/local/lib/python2.7/site-packages/xgboost/core.py", line 344, in _init_from_npy2d
    raise ValueError('Input numpy.ndarray must be 2 dimensional')
ValueError: Input numpy.ndarray must be 2 dimensional
Exception AttributeError: "'DMatrix' object has no attribute 'handle'" in <bound method DMatrix.__del__ of <xgboost.core.DMatrix object at 0x7f413f9bfe50>> ignored
Encountered error not related to missing packages. Please refer to the container log to diagnose.
```

**Comment by jayantjain93** [comment]
So I found the issue with this. There is type difference from what xgboost returns in batch prediction to what is being used.
The following is the solution to the issue:
```
def predict(xs):
    print(str(xs))
    op = [model.predict(xgb.DMatrix(xs,label=None,feature_names=None)) ]
    op2 = []
    for x in op[0]:
        op2.append(str([x]))
    return op2
```

**Comment by RehanSD** [comment]
Hi @jayantjain93, @donigian, changing your predict function so that it is just 
```python
def predict(xs):
     return model.predict(xgb.DMatrix(xs))
```
should fix the issue. The website will be updated shortly.

**Comment by donigian** [comment]
@RehanSD 
I think you meant...

```
def predict(xs):
     return bst.predict(xgb.DMatrix(xs))
```

as model is undefined. thank you :)
