### ISSUE TITLE
Website tutorial keeps timing out on trying to add model image (all i changed with the prometheus port)

### ISSUE THREAD

**Issue by ghostfreak3000** [ucbrise/clipper#561]
The Getting started tutorial for clipper just keeps making a readtimeout error.
Here's the python.

```python
from clipper_admin import ClipperConnection, DockerContainerManager

from clipper_admin.deployers import python as python_deployer

# set prometheus port to 9290 because the default 9090 is used
print("Setting prometheus port")
clipper_conn = ClipperConnection(DockerContainerManager(prometheus_port=9290))

#stop any existing containers
print("Stoping all containers")
clipper_conn.stop_all()

#start clipper
print("Starting clipper")
clipper_conn.start_clipper()

#add hello-world app
print("Adding hello world app")
clipper_conn.register_application(name="hello-world", input_type="doubles", default_output="-1.0", slo_micros=100000)

#define feature_sum function
def feature_sum(xs):
    return [str(sum(x)) for x in xs]

#deploy feature_sum function to sum-model model
print("Deploying feature_sum model")
python_deployer.deploy_python_closure(clipper_conn, name="sum-model", version=1, input_type="doubles", func=feature_sum)

#route hello world app to feature_sum model
print("Routing hello world app to feature_sum model")
clipper_conn.link_model_to_app(app_name="hello-world", model_name="sum-model")

```

Here's the bash
```bash

clipper@ip-172-31-26-36:~/repo$ python test.py
Setting prometheus port
Stoping all containers
18-08-28:14:08:41 INFO     [clipper_admin.py:1258] Stopped all Clipper cluster and all model containers
Starting clipper
18-08-28:14:08:41 INFO     [docker_container_manager.py:119] Starting managed Redis instance in Docker
18-08-28:14:08:57 INFO     [clipper_admin.py:126] Clipper is running
Adding hello world app
18-08-28:14:08:57 INFO     [clipper_admin.py:201] Application hello-world was successfully registered
Deploying feature_sum model
18-08-28:14:08:57 INFO     [deployer_utils.py:44] Saving function to /tmp/clipper/tmpf6HPvf
18-08-28:14:08:57 INFO     [deployer_utils.py:54] Serialized and supplied predict function
18-08-28:14:08:57 INFO     [python.py:192] Python closure saved
18-08-28:14:08:57 INFO     [python.py:198] Using Python 2 base image
18-08-28:14:08:57 INFO     [clipper_admin.py:452] Building model Docker image with model data from /tmp/clipper/tmpf6HPvf
18-08-28:14:09:04 INFO     [clipper_admin.py:456] {u'stream': u'Step 1/2 : FROM clipper/python-closure-container:0.3.0'}
18-08-28:14:09:04 INFO     [clipper_admin.py:456] {u'stream': u'\n'}
18-08-28:14:09:04 INFO     [clipper_admin.py:456] {u'stream': u' ---> bfcdf8ffce0c\n'}
18-08-28:14:09:04 INFO     [clipper_admin.py:456] {u'stream': u'Step 2/2 : COPY /tmp/clipper/tmpf6HPvf /model/'}
18-08-28:14:09:04 INFO     [clipper_admin.py:456] {u'stream': u'\n'}
18-08-28:14:09:04 INFO     [clipper_admin.py:456] {u'stream': u' ---> 793a132eea38\n'}
18-08-28:14:09:04 INFO     [clipper_admin.py:456] {u'aux': {u'ID': u'sha256:793a132eea3837a49b311e28325d50c3082601b3145d756283a9f3942bc23d95'}}
18-08-28:14:09:04 INFO     [clipper_admin.py:456] {u'stream': u'Successfully built 793a132eea38\n'}
18-08-28:14:09:04 INFO     [clipper_admin.py:456] {u'stream': u'Successfully tagged sum-model:1\n'}
18-08-28:14:09:04 INFO     [clipper_admin.py:458] Pushing model Docker image to sum-model:1
18-08-28:14:09:04 INFO     [docker_container_manager.py:257] Found 0 replicas for sum-model:1. Adding 1
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    python_deployer.deploy_python_closure(clipper_conn, name="sum-model", version=1, input_type="doubles", func=feature_sum)
  File "/home/clipper/.local/lib/python2.7/site-packages/clipper_admin/deployers/python.py", line 222, in deploy_python_closure
    registry, num_replicas, batch_size, pkgs_to_install)
  File "/home/clipper/.local/lib/python2.7/site-packages/clipper_admin/clipper_admin.py", line 338, in build_and_deploy_model
    num_replicas, batch_size)
  File "/home/clipper/.local/lib/python2.7/site-packages/clipper_admin/clipper_admin.py", line 544, in deploy_model
    num_replicas=num_replicas)
  File "/home/clipper/.local/lib/python2.7/site-packages/clipper_admin/docker/docker_container_manager.py", line 192, in deploy_model
    self.set_num_replicas(name, version, input_type, image, num_replicas)
  File "/home/clipper/.local/lib/python2.7/site-packages/clipper_admin/docker/docker_container_manager.py", line 262, in set_num_replicas
    image)
  File "/home/clipper/.local/lib/python2.7/site-packages/clipper_admin/docker/docker_container_manager.py", line 238, in _add_replica
    **self.extra_container_kwargs)
  File "/home/clipper/.local/lib/python2.7/site-packages/docker/models/containers.py", line 772, in run
    container.start()
  File "/home/clipper/.local/lib/python2.7/site-packages/docker/models/containers.py", line 374, in start
    return self.client.api.start(self.id, **kwargs)
  File "/home/clipper/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/clipper/.local/lib/python2.7/site-packages/docker/api/container.py", line 1065, in start
    res = self._post(url)
  File "/home/clipper/.local/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/home/clipper/.local/lib/python2.7/site-packages/docker/api/client.py", line 194, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/home/clipper/.local/lib/python2.7/site-packages/requests/sessions.py", line 559, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/clipper/.local/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/clipper/.local/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/clipper/.local/lib/python2.7/site-packages/requests/adapters.py", line 526, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
clipper@ip-172-31-26-36:~/repo$
```
How do i increase that timeout?.. or better yet, what or where exactly is the problem?

**Comment by withsmilo** [comment]
@ghostfreak3000 :  
You have failed to run a Docker container of 'sum-model'. I think that you have too many Docker containers and images on local. Please retry the Clipper tutorial after cleaning up your Docker container and images.
```
# Remove all the Docker containers
$ docker rm -f $(docker ps -a -q)

# Remove all the Docker images
$ docker system prune -a
```

**Comment by ghostfreak3000** [comment]
Doing that.. while your here
I assume that at this point
```bash
18-08-28:15:24:06 INFO     [docker_container_manager.py:119] Starting managed Redis instance in Docker
```
Clipper is downloading the container images.
Is there a verbose option to print the progress?

**Comment by withsmilo** [comment]
@ghostfreak3000 :  
`start_clipper()` does not have a verbose option.

**Comment by ghostfreak3000** [comment]
Cool.
Tutorial hanged for 1hr on
```bash
18-08-28:15:25:55 INFO     [docker_container_manager.py:257] Found 0 replicas for sum-model:1. Adding 1
```
Have to disconnect from the server to go home. so we back to square one.
I've attached the full log
[log.txt](https://github.com/ucbrise/clipper/files/2328905/log.txt)

**Comment by ebanner** [comment]
Also hanging indefinitely for me on the call to `python_deployer.deploy_python_closure()`.

**Comment by ebanner** [comment]
It's hanging in [this while loop](https://github.com/ucbrise/clipper/blob/3c5a1cc6ce59e0ccd778f526a50808d0e7b2576f/clipper_admin/clipper_admin/docker/docker_container_manager.py#L362-L364).

```python
while container.attrs.get("State").get("Status") != "running" or \
        self.docker_client.api.inspect_container(name).get("State").get("Health").get("Status") != "healthy":
    time.sleep(3)
```

Here are the values of those expressions.

```python
>>> container.attrs.get("State").get("Status")
u'running'
>>> self.docker_client.api.inspect_container(name).get("State").get("Health").get("Status")
u'unhealthy'
```

I tried commenting out those lines, but here's what I got.

```shell
$ curl -X POST --header "Content-Type:application/json" -d '{"input": [1.1, 2.2, 3.3]}' 127.0.0.1:1337/hello-world/predict
curl: (52) Empty reply from server
```

It actually works when I run it locally. The version of `clipper_admin` is the same in both (`0.0.3`) and docker (`18.06.1-ce`).

Any recommendation on how to debug further?

**Comment by withsmilo** [comment]
@ebanner : 
1. I think that your model service has something wrong. Please check your model service's log.
2. `It actually works when I run it locally.` -> Where are you running Clipper now?

**Comment by ebanner** [comment]
> Where are you running Clipper now?

I'm running it on a AWS ec2 instance.

> Please check your model service's log.

I ran `clipper_conn.get_clipper_logs()`. The most conspicuous log is the redis log.

```
1:C 18 Sep 18:02:25.137 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 18 Sep 18:02:25.137 # Redis version=4.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 18 Sep 18:02:25.137 # Configuration loaded
1:M 18 Sep 18:02:25.138 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
1:M 18 Sep 18:02:25.138 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
1:M 18 Sep 18:02:25.138 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
1:M 18 Sep 18:02:25.139 * Running mode=standalone, port=6379.
1:M 18 Sep 18:02:25.139 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 18 Sep 18:02:25.139 # Server initialized
1:M 18 Sep 18:02:25.139 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 18 Sep 18:02:25.139 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 18 Sep 18:02:25.139 * Ready to accept connections
```

This is the same redis log file on my current machine, which works.

```
1:C 18 Sep 18:11:56.546 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 18 Sep 18:11:56.546 # Redis version=4.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 18 Sep 18:11:56.546 # Configuration loaded
1:M 18 Sep 18:11:56.548 * Running mode=standalone, port=6379.
1:M 18 Sep 18:11:56.548 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 18 Sep 18:11:56.548 # Server initialized
1:M 18 Sep 18:11:56.548 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with
1:M 18 Sep 18:11:56.548 * Ready to accept connections
```

The model container on the ec2 machine gets terminated almost immediately.

**Comment by ebanner** [comment]
For completeness, here are all the logs from `clipper_logs/` on the ec2 instance.

image_sha256:3d960da25d:container_afcc8acae6.log

```
^[[1m[18:03:07.517][info]       [REDIS] Successfully issued command "SELECT 1"
^[[00m^[[1m[18:03:07.517][info]     [STATEDB] Persistent state DB created
^[[00m^[[1m[18:03:27.583][info]   [MGMTFRNTD] Add application POST request
^[[00m^[[1m[18:03:27.583][info]       [REDIS] Successfully issued command "SELECT 5"
^[[00m^[[1m[18:03:27.583][info]       [REDIS] Successfully issued command "HGETALL hello-world"
^[[00m^[[1m[18:03:27.583][info]       [REDIS] Successfully issued command "SELECT 5"
^[[00m^[[1m[18:03:27.583][info]       [REDIS] Successfully issued command "HMSET hello-world input_type doubles policy DefaultOutputSelectionPolicy default_output -1.0 latency_slo_micros 100000"
^[[00m^[[1m[18:04:54.670][info]   [MGMTFRNTD] Add application POST request
^[[00m^[[1m[18:04:54.670][info]       [REDIS] Successfully issued command "SELECT 5"
^[[00m^[[1m[18:04:54.670][info]       [REDIS] Successfully issued command "HGETALL hello-world"
^[[00m^[[1m[18:04:54.670][info]       [REDIS]    input_type: doubles
^[[00m^[[1m[18:04:54.670][info]       [REDIS]    policy: DefaultOutputSelectionPolicy
^[[00m^[[1m[18:04:54.670][info]       [REDIS]    default_output: -1.0
^[[00m^[[1m[18:04:54.670][info]       [REDIS]    latency_slo_micros: 100000
```

[image_sha256:7eefa1a263:container_3bc906e38d.log](https://gist.github.com/ebanner/b95dc59f8dcf75a4c5874595bdca2d45)

image_sha256:c29b40eb63:container_afff200e76.log

```
18-09-18:18:03:12 INFO     [front_end_exporter.py:28] Scraping http://query_frontend-18657:1337/metrics
```

image_sha256:c8ecf7c719:container_f4b8766433.log

```
level=info ts=2018-09-18T18:03:16.104845148Z caller=main.go:225 msg="Starting Prometheus" version="(version=2.1.0, branch=HEAD, revision=85f23d82a045d103ea7f3c89a91fba4a93e6367a)"
level=info ts=2018-09-18T18:03:16.104899647Z caller=main.go:226 build_context="(go=go1.9.2, user=root@6e784304d3ff, date=20180119-12:01:23)"
level=info ts=2018-09-18T18:03:16.105095669Z caller=main.go:227 host_details="(Linux 4.14.33-51.34.amzn1.x86_64 #1 SMP Fri Apr 13 18:18:26 UTC 2018 x86_64 f4b876643364 (none))"
level=info ts=2018-09-18T18:03:16.105114661Z caller=main.go:228 fd_limits="(soft=1024, hard=4096)"
level=info ts=2018-09-18T18:03:16.10791245Z caller=main.go:499 msg="Starting TSDB ..."
level=info ts=2018-09-18T18:03:16.107930509Z caller=web.go:383 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2018-09-18T18:03:16.115317308Z caller=main.go:509 msg="TSDB started"
level=info ts=2018-09-18T18:03:16.115377209Z caller=main.go:585 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
level=info ts=2018-09-18T18:03:16.115739501Z caller=main.go:486 msg="Server is ready to receive web requests."
level=info ts=2018-09-18T18:03:16.115788255Z caller=manager.go:59 component="scrape manager" msg="Starting scrape manager..."
level=info ts=2018-09-18T18:03:40.43601539Z caller=main.go:585 msg="Loading configuration file" filename=/etc/prometheus/prometheus.yml
```

image_sha256:db23f46600:container_6fa380cdc4.log

```
1:C 18 Sep 18:02:25.137 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 18 Sep 18:02:25.137 # Redis version=4.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 18 Sep 18:02:25.137 # Configuration loaded
1:M 18 Sep 18:02:25.138 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
1:M 18 Sep 18:02:25.138 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
1:M 18 Sep 18:02:25.138 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
1:M 18 Sep 18:02:25.139 * Running mode=standalone, port=6379.
1:M 18 Sep 18:02:25.139 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 18 Sep 18:02:25.139 # Server initialized
1:M 18 Sep 18:02:25.139 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 18 Sep 18:02:25.139 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 18 Sep 18:02:25.139 * Ready to accept connections

```

**Comment by withsmilo** [comment]
@ebanner : 
I think that this problem is dependent of your dev environment. 
> The model container on the ec2 machine gets terminated almost immediately.

First of all, you must retreive your model container's logs.

**Comment by finsqm** [comment]
I'm also having the same issue, `python_deployer.deploy_python_closure` is hanging when I run the XGBoost tutorial locally.

**Comment by finsqm** [comment]
I think the issue is with this line: https://github.com/ucbrise/clipper/blob/develop/clipper_admin/clipper_admin/docker/docker_container_manager.py#L363

The `State.Health.Status` is only defined if there's a healthcheck in the docker image, which I don't think there is for the default images.

**Comment by ebanner** [comment]
Huh, here's the logs from my exited container.

```
$ docker logs fc747ef19f2b
Traceback (most recent call last):
  File "/container/python_closure_container.py", line 56, in <module>
    rpc_service.get_input_type())
  File "/container/python_closure_container.py", line 28, in __init__
Starting Python Closure container
Connecting to Clipper with default port: 7000
    self.predict_func = load_predict_func(predict_path)
  File "/container/python_closure_container.py", line 14, in load_predict_func
    return cloudpickle.load(serialized_func_file)
  File "/usr/local/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/local/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/local/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
  File "/usr/local/lib/python2.7/site-packages/cloudpickle/cloudpickle.py", line 1044, in _make_skel_func
    base_globals['__builtins__'] = __builtins__
TypeError: 'str' object does not support item assignment
Encountered error not related to missing packages. Please refer to the container log to diagnose.
```

I get the same error when running with python 3.6.

```
$ docker logs 97b67e06cb51
Starting Python Closure container
Connecting to Clipper with default port: 7000
Traceback (most recent call last):
  File "/container/python_closure_container.py", line 56, in <module>
    rpc_service.get_input_type())
  File "/container/python_closure_container.py", line 28, in __init__
    self.predict_func = load_predict_func(predict_path)
  File "/container/python_closure_container.py", line 17, in load_predict_func
    return cloudpickle.load(serialized_func_file)
  File "/usr/local/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 1060, in _make_skel_func
    base_globals['__builtins__'] = __builtins__
TypeError: 'str' object does not support item assignment
Encountered error not related to missing packages. Please refer to the container log to diagnose.
```

**Comment by withsmilo** [comment]
@finsqm @ebanner : Please refer to this issue, 
https://github.com/ucbrise/clipper/issues/568

**Comment by ebanner** [comment]
Wow, thanks @withsmilo! That fixed the issue.

**Comment by finsqm** [comment]
Same here, thanks 👍
