### ISSUE TITLE
Question about deployed model container?

### ISSUE THREAD

**Issue by YupaTapuY** [ucbrise/clipper#591]
hi, i want to ask something about how clipper managing docker container : 
1. i already deployed a model with 3 replicas container(A,B,C), how i control it to predict an input into a specified replicas out of the 3(for example container A)
2. will clipper have error handling or error logs feature when container crashed or predict error in the future ?

**Comment by withsmilo** [comment]
@YupaTapuY : 
1. You cannot control this case manually. Why do you need this scenario?
2. If you would like to handle some errors in detail, I recommend you have to implement your custom model container. ([link](http://clipper.ai/tutorials/custom_model_container/))

**Comment by YupaTapuY** [comment]
thank you for answering

1. then how load balancing work for the three replicas when it had multiple predict requests or how the container manager route the predict request into which container replicas?

2. ohh ok then, i'll implement it with custom container 

Thank you very much for the response

**Comment by withsmilo** [comment]
@YupaTapuY : 
1. Clipper has a model queue and working threads related each replica. First of all, TaskExecutor will add your multiple predict requests (aka. tasks) to the related model queue. ([code](https://github.com/ucbrise/clipper/blob/develop/src/libclipper/include/clipper/task_executor.hpp#L411)) And then, if a working thread is idle, it will try to process the requests retrieved from the model queue. If many working threads are idle, the sequence will be determined by a condition variable.

**Comment by YupaTapuY** [comment]
Thanks, now i know how it processed

Actually i need to know if i can customize the process because i want to make the model versioning system that shifting the task little by little to the new version of the model, not shifting entirely to the new version model

but thanks for answering, really appreciated

**Comment by withsmilo** [comment]
@YupaTapuY : 
Does it means rolling update? I think that Clipper supports 'blue-green' deployment policy basically. But, to imitate rolling update, you can register two Clipper apps 'v1', 'v2' and setup a new gateway server in front of Clipper_qf to control inside traffic between 'v1' and 'v2' manually .

**Comment by YupaTapuY** [comment]
oh, alright thanks for the answer, yes i think the scenario is similar to rolling update, and one more thing, may i know if i can access redis db when deploying a model and what stored in redis db ?

anyway, thanks for your answer and support

**Comment by withsmilo** [comment]
@YupaTapuY : 
Yes, you can.

**Comment by YupaTapuY** [comment]
may i know what stored in redis db ? 
thanks anyway

**Comment by withsmilo** [comment]
@YupaTapuY : 
1. Install [redis-py](https://github.com/andymccurdy/redis-py).
2. Get your Redis' IP address.
3. Redis DB table is here.
```
enum RedisDBTable {
  REDIS_STATE_DB_NUM = 1,
  REDIS_MODEL_DB_NUM = 2,
  REDIS_CONTAINER_DB_NUM = 3,
  REDIS_RESOURCE_DB_NUM = 4,
  REDIS_APPLICATION_DB_NUM = 5,
  REDIS_METADATA_DB_NUM = 6,  // used to store Clipper configuration metadata
  REDIS_APP_MODEL_LINKS_DB_NUM = 7,
};
```
4. Now you can find what stored in Redis. For example, you can check REDIS_CONTAINER_DB(3) by this command.
```
>>> import redis
>>> r = redis.StrictRedis(host='YOUR_REDIS_IP', port=6379, db=3)
>>> r.keys()
```

**Comment by YupaTapuY** [comment]
ok thanks, it work, now i can see what stored in the redis db

but i have another problems, after i check all the redis db i got an error when i use clipper.conn start clipper()

`18-11-05:23:12:12 INFO     [docker_container_manager.py:119] Starting managed Redis instance in Docker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/clipper_admin/clipper_admin.py", line 114, in start_clipper
    cache_size, num_frontend_replicas)
  File "/usr/lib/python2.7/site-packages/clipper_admin/docker/docker_container_manager.py", line 127, in start_clipper
    **self.extra_container_kwargs)
  File "/usr/lib/python2.7/site-packages/docker/models/containers.py", line 772, in run
    container.start()
  File "/usr/lib/python2.7/site-packages/docker/models/containers.py", line 374, in start
    return self.client.api.start(self.id, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/docker/api/container.py", line 1066, in start
    self._raise_for_status(res)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 231, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint redis-25906 (435e60595d5a98a282d4663eb897e9cdbeefad813e689393156914a2f6d782b4):  (iptables failed: iptables --wait -t filter -A DOCKER ! -i br-99943f5f6493 -o br-99943f5f6493 -p tcp -d 172.19.0.2 --dport 6379 -j ACCEPT: iptables: No chain/target/match by that name.
 (exit status 1))")`

is it because my mistake when i checking redis db ? im sorry if i bother you with all these question
btw, thanks for your help so far

**Comment by withsmilo** [comment]
@YupaTapuY : 
hmm. Strange problem. Please restart Docker on your local.

**Comment by YupaTapuY** [comment]
thanks, it's worked now, i just restart docker service and it worked

**Comment by YupaTapuY** [comment]
one more question, do clipper store information of how many times a deployed model's predict function gets called or something like that ? 

thanks before

**Comment by withsmilo** [comment]
@YupaTapuY : 
Do you want to monitor Clipper's metrics? Clipper provides the function. Please refer to [here](https://github.com/ucbrise/clipper/tree/develop/monitoring).
