### ISSUE TITLE
failed to build clipper Docker image

### ISSUE THREAD

**Issue by Archelunch** [ucbrise/clipper#640]
I tried to build docker image 
`python_deployer.create_endpoint(clipper_conn, "simple-example", "doubles",
                                    feature_sum, pkgs_to_install=['catboost'])`
But after running script I got this:
`Traceback (most recent call last):
  File "test_api.py", line 46, in <module>
    feature_sum, pkgs_to_install=['catboost'])
  File "/usr/local/lib/python3.6/site-packages/clipper_admin/deployers/python.py", line 91, in create_endpoint
    batch_size, pkgs_to_install)
  File "/usr/local/lib/python3.6/site-packages/clipper_admin/deployers/python.py", line 222, in deploy_python_closure
    registry, num_replicas, batch_size, pkgs_to_install)
  File "/usr/local/lib/python3.6/site-packages/clipper_admin/clipper_admin.py", line 355, in build_and_deploy_model
    container_registry, pkgs_to_install)
  File "/usr/local/lib/python3.6/site-packages/clipper_admin/clipper_admin.py", line 474, in build_model
    fileobj=context_file, custom_context=True, tag=image)
  File "/usr/local/lib/python3.6/site-packages/docker/models/images.py", line 287, in build
    raise BuildError(chunk['error'], result_stream)
docker.errors.BuildError: The command '/bin/sh -c apt-get -y install build-essential && pip install catboost' returned a non-zero code: 2`

Without 'pkgs_to_instal' everything is fine

**Comment by withsmilo** [comment]
Hi, @Archelunch : 
1. Please share your `test_api.py` with us.
2. Please check your firewall if you set it in test machine.

**Comment by Archelunch** [comment]
It is from examples, but only with attempt to install packages
I don't have problems with firewall, because without 'pkgs_to_instal' everything works fine

`from __future__ import print_function
from clipper_admin import ClipperConnection, DockerContainerManager
from clipper_admin.deployers import python as python_deployer
import json
import requests
from datetime import datetime
import time
import numpy as np
import signal
import sys


def predict(addr, x, batch=False):
    url = "http://%s/simple-example/predict" % addr

    if batch:
        req_json = json.dumps({'input_batch': x})
    else:
        req_json = json.dumps({'input': list(x)})

    headers = {'Content-type': 'application/json'}
    start = datetime.now()
    r = requests.post(url, headers=headers, data=req_json)
    end = datetime.now()
    latency = (end - start).total_seconds() * 1000.0
    print("'%s', %f ms" % (r.text, latency))


def feature_sum(xs):
    return [str(sum(x)) for x in xs]


# Stop Clipper on Ctrl-C
def signal_handler(signal, frame):
    print("Stopping Clipper...")
    clipper_conn = ClipperConnection(DockerContainerManager())
    clipper_conn.stop_all()
    sys.exit(0)


if __name__ == '__main__':
    signal.signal(signal.SIGINT, signal_handler)
    clipper_conn = ClipperConnection(DockerContainerManager())
    clipper_conn.start_clipper()
    python_deployer.create_endpoint(clipper_conn, "simple-example", "doubles",
                                    feature_sum, pkgs_to_install=['catboost'])
    time.sleep(2)

    # For batch inputs set this number > 1
    batch_size = 1

    try:
        predict(clipper_conn.get_query_addr(), np.random.random(200))
    except Exception as e:
        clipper_conn.stop_all()`

**Comment by Archelunch** [comment]
It is from examples, but only with attempt to install packages
I don't have problems with firewall, because without 'pkgs_to_instal' everything works fine

```
from __future__ import print_function
from clipper_admin import ClipperConnection, DockerContainerManager
from clipper_admin.deployers import python as python_deployer
import json
import requests
from datetime import datetime
import time
import numpy as np
import signal
import sys


def predict(addr, x, batch=False):
    url = "http://%s/simple-example/predict" % addr

    if batch:
        req_json = json.dumps({'input_batch': x})
    else:
        req_json = json.dumps({'input': list(x)})

    headers = {'Content-type': 'application/json'}
    start = datetime.now()
    r = requests.post(url, headers=headers, data=req_json)
    end = datetime.now()
    latency = (end - start).total_seconds() * 1000.0
    print("'%s', %f ms" % (r.text, latency))


def feature_sum(xs):
    return [str(sum(x)) for x in xs]


# Stop Clipper on Ctrl-C
def signal_handler(signal, frame):
    print("Stopping Clipper...")
    clipper_conn = ClipperConnection(DockerContainerManager())
    clipper_conn.stop_all()
    sys.exit(0)


if __name__ == '__main__':
    signal.signal(signal.SIGINT, signal_handler)
    clipper_conn = ClipperConnection(DockerContainerManager())
    clipper_conn.start_clipper()
    python_deployer.create_endpoint(clipper_conn, "simple-example", "doubles",
                                    feature_sum, pkgs_to_install=['catboost'])
    time.sleep(2)

    # For batch inputs set this number > 1
    batch_size = 1

    try:
        predict(clipper_conn.get_query_addr(), np.random.random(200))
    except Exception as e:
        clipper_conn.stop_all()
```

**Comment by withsmilo** [comment]
@Archelunch . I had the success to run your `test_api.py` and my logs are here,
```
$ python test_api.py
19-02-27:00:14:19 INFO     [docker_container_manager.py:151] [default-cluster] Starting managed Redis instance in Docker
19-02-27:00:14:22 INFO     [docker_container_manager.py:229] [default-cluster] Metric Configuration Saved at /private/var/folders/3q/f41dn1j54z72yf8bs2_80l1r0000gn/T/tmpursfpgyw.yml
19-02-27:00:14:22 INFO     [clipper_admin.py:138] [default-cluster] Clipper is running
19-02-27:00:14:22 INFO     [clipper_admin.py:215] [default-cluster] Application simple-example was successfully registered
19-02-27:00:14:22 INFO     [deployer_utils.py:41] Saving function to /var/folders/3q/f41dn1j54z72yf8bs2_80l1r0000gn/T/tmp_f5st66tclipper
19-02-27:00:14:22 INFO     [deployer_utils.py:51] Serialized and supplied predict function
19-02-27:00:14:22 INFO     [python.py:205] Python closure saved
19-02-27:00:14:22 INFO     [python.py:219] Using Python 3.6 base image
19-02-27:00:14:22 INFO     [clipper_admin.py:521] [default-cluster] Building model Docker image with model data from /var/folders/3q/f41dn1j54z72yf8bs2_80l1r0000gn/T/tmp_f5st66tclipper
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] Step 1/3 : FROM clipper/python36-closure-container:develop
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster]  ---> fdf859266796
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] Step 2/3 : RUN apt-get -y install build-essential && pip install catboost
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster]  ---> Running in e50ac4664a03
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] Reading package lists...
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] Building dependency tree...
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster]
Reading state information...
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] build-essential is already the newest version (12.3).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] Collecting catboost
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster]   Downloading https://files.pythonhosted.org/packages/98/03/777a0e1c12571a7f3320a4fa6d5f123dba2dd7c0bca34f4f698a6396eb48/catboost-0.12.2-cp36-none-manylinux1_x86_64.whl (55.5MB)
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] Collecting pandas>=0.19.1 (from catboost)
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster]   Downloading https://files.pythonhosted.org/packages/e6/de/a0d3defd8f338eaf53ef716e40ef6d6c277c35d50e09b586e170169cdf0d/pandas-0.24.1-cp36-cp36m-manylinux1_x86_64.whl (10.1MB)
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] Requirement already satisfied: six in /usr/local/lib/python3.6/site-packages (from catboost) (1.12.0)
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.6/site-packages (from catboost) (1.14.6)
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] Collecting enum34 (from catboost)
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster]   Downloading https://files.pythonhosted.org/packages/af/42/cb9355df32c69b553e72a2e28daee25d1611d2c0d9c272aa1d34204205b2/enum34-1.1.6-py3-none-any.whl
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] Collecting pytz>=2011k (from pandas>=0.19.1->catboost)
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster]   Downloading https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl (510kB)
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python3.6/site-packages (from pandas>=0.19.1->catboost) (2.8.0)
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] Installing collected packages: pytz, pandas, enum34, catboost
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] Successfully installed catboost-0.12.2 enum34-1.1.6 pandas-0.24.1 pytz-2018.9
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] You are using pip version 19.0.2, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster]  ---> 674e568f4707
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] Step 3/3 : COPY /var/folders/3q/f41dn1j54z72yf8bs2_80l1r0000gn/T/tmp_f5st66tclipper /model/
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster]  ---> 029c16693d7c
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] Successfully built 029c16693d7c
19-02-27:00:17:18 INFO     [clipper_admin.py:526] [default-cluster] Successfully tagged simple-example:1
19-02-27:00:17:18 INFO     [clipper_admin.py:528] [default-cluster] Pushing model Docker image to simple-example:1
19-02-27:00:17:21 INFO     [docker_container_manager.py:353] [default-cluster] Found 0 replicas for simple-example:1. Adding 1
19-02-27:00:17:37 INFO     [clipper_admin.py:725] [default-cluster] Successfully registered model simple-example:1
19-02-27:00:17:37 INFO     [clipper_admin.py:635] [default-cluster] Done deploying model simple-example:1.
19-02-27:00:17:37 INFO     [clipper_admin.py:277] [default-cluster] Model simple-example is now linked to application simple-example
'{"query_id":0,"output":94.91201718715509,"use_default":false}', 66.836000 ms
```
I used custom version of Clipper for test. If you let me know which version you used, I'll test it with it.

**Comment by Archelunch** [comment]
I installed this version 
https://github.com/ucbrise/clipper.git@develop#subdirectory=clipper_admin

**Comment by rkooo567** [comment]
@Archelunch Were you be able to resolve the issue?

**Comment by Archelunch** [comment]
@rkooo567 yes, it works now
