### ISSUE TITLE
prometheus.yml mount error on start_clipper

### ISSUE THREAD

**Issue by ZaninAndrea** [ucbrise/clipper#705]
I get a `not a directory` error when running the setup script shown in the docs.

## Logs
```bash
> pip install git+https://github.com/ucbrise/clipper.git@develop#subdirectory=clipper_admin
[...]

> docker ps      
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

> python clipper_setup.py
19-05-23:13:49:10 INFO     [docker_container_manager.py:184] [default-cluster] Starting managed Redis instance in Docker
19-05-23:13:49:15 INFO     [docker_container_manager.py:276] [default-cluster] Metric Configuration Saved at /tmp/tmp_jv_x578.yml
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/home/user/.local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.35/containers/7359801c2381bf53d4fa3e5d49116bf99bd984dd452008b71cc436583346b65a/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "clipper_setup.py", line 3, in <module>
    clipper_conn.start_clipper()
  File "/home/user/.conda/envs/adalitix/lib/python3.6/site-packages/clipper_admin/clipper_admin.py", line 139, in start_clipper
    qf_http_timeout_content, num_frontend_replicas)
  File "/home/user/.conda/envs/adalitix/lib/python3.6/site-packages/clipper_admin/docker/docker_container_manager.py", line 290, in start_clipper
    self.extra_container_kwargs)
  File "/home/user/.conda/envs/adalitix/lib/python3.6/site-packages/clipper_admin/docker/docker_metric_utils.py", line 111, in run_metric_image
    **extra_container_kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/docker/models/containers.py", line 791, in run
    container.start()
  File "/home/user/.local/lib/python3.6/site-packages/docker/models/containers.py", line 392, in start
    return self.client.api.start(self.id, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/docker/api/container.py", line 1091, in start
    self._raise_for_status(res)
  File "/home/user/.local/lib/python3.6/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/user/.local/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/tmp/tmp_jv_x578.yml\\\" to rootfs \\\"/var/snap/docker/common/var-lib-docker/aufs/mnt/3a49dc908701af330efce3a99a0378b31cb00adce15b8a72fcfb3b84a55177f8\\\" at \\\"/var/snap/docker/common/var-lib-docker/aufs/mnt/3a49dc908701af330efce3a99a0378b31cb00adce15b8a72fcfb3b84a55177f8/etc/prometheus/prometheus.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type")

> docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                                            NAMES
be95141e0148        clipper/frontend-exporter:develop     "python /usr/src/app…"   2 minutes ago       Up 2 minutes                                                         query_frontend_exporter-58608
c123fad677cc        clipper/query_frontend:develop        "/clipper/query_fron…"   2 minutes ago       Up 2 minutes        0.0.0.0:1337->1337/tcp, 0.0.0.0:7000->7000/tcp   query_frontend-58608
aa7c68af2981        clipper/management_frontend:develop   "/clipper/mgmt_front…"   2 minutes ago       Up 2 minutes        0.0.0.0:1338->1338/tcp                           mgmt_frontend-73212
143bcedce83e        redis:alpine                          "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes        0.0.0.0:40445->6379/tcp                          redis-56863

```

`clipper_setup.py` file:

```python
from clipper_admin import ClipperConnection, DockerContainerManager
clipper_conn = ClipperConnection(DockerContainerManager())
clipper_conn.start_clipper()
```

## Setup
I am using python 3.6.0 (installed with conda) on ubuntu 18.04, my docker version is 18.09.3, I have access to the `/tmp` folder and can create a file in it, furthermore the file that the error refers to (`/tmp/tmp_jv_x578.yml`) exists and contains the following:

```yaml
global:
  evaluation_interval: 5s
  scrape_interval: 5s
scrape_configs:
- job_name: query
  static_configs:
  - targets:
    - query_frontend_exporter-58608:1390
```

**Comment by rkooo567** [comment]
Are you using remote docker daemon?

**Comment by ZaninAndrea** [comment]
No, I'm working locally

**Comment by rkooo567** [comment]
https://github.com/ucbrise/clipper/issues/701

Could you try @withsmilo's solution in this post? Also, can you try to update the python version?

**Comment by ZaninAndrea** [comment]
I tried both python 3.6 and 3.7.

I don't have the linux machine I'm running clipper on with me now, I will try @withsmilo's solution first thing tomorrow, still I doubt it will solve the issue as the file that gives error exists and is a file:

> furthermore the file that the error refers to (`/tmp/tmp_jv_x578.yml`) exists and contains the following:
> 
> ```yaml
> global:
>   evaluation_interval: 5s
>   scrape_interval: 5s
> scrape_configs:
> - job_name: query
>   static_configs:
>   - targets:
>     - query_frontend_exporter-58608:1390
> ```

**Comment by rkooo567** [comment]
@ZaninAndrea Clipper is not supporting python 3.7 yet. Please try like python >= 3.6.7, <3.7. 

The thing is that `is not a directory` happens mostly because the file you try to mount is a directory cuz docker daemon couldn't find the file from the path, and it creates a directory. But for your case, you are not using remote docker as well as Mac/Windows, so, I cannot think of/find resources about how it can occur. 

If clipper creates a file in `/tmp` folder correctly, the possibility is that inside container's path `/etc/prometheus/prometheus.yml` is a directory. It can happen if the file is deleted somehow when container is initializing. In that case, @withsmilo's solution can work. 

Also, I could not reproduce the problem in my ubuntu 18.04.2 vm with `example_client.py` in `basic_example` directory. So, if @withsmilo's solution doesn't work, probably you should ask it to the docker community because I think it is a docker setting issue.

**Comment by ZaninAndrea** [comment]
@rkooo567 Tried python 3.6.7 and removing all volumes as per @withsmilo's solution, but I get the same error

**Comment by rkooo567** [comment]
@ZaninAndrea Thank you for trying that! I believe it should be some docker setting issues (because as I said, I couldn't reproduce your log from the same setup), so please raise an issue in the docker community. Let me know if you have any further question!

**Comment by rkooo567** [comment]
Hi, @ZaninAndrea. Did you resolve the problem? If so, would you mind sharing your solution?

**Comment by ZaninAndrea** [comment]
In the end I didn't manage to solve the issue, but I used a work around: installing clipper in a docker-in-docker image.

**Comment by rkooo567** [comment]
Resolved.
