### ISSUE TITLE
basic query example

### ISSUE THREAD

**Issue by feifeibear** [ucbrise/clipper#771]
Hi, I try to follow the basic query example.
After I launch the python script. 
`
python example_client.py
`
I met the following problem.
`
20-10-10:10:49:22 WARNING  [decorators.py:34] [default-cluster] Clipper still initializing:
 query frontend end point http://localhost:1337/metrics health check failed, Retrying in 1 seconds..
`

**Comment by feifeibear** [comment]
After I switch to another computer. I met the following error in case of using `python example_client.py`

20-10-10:11:23:13 INFO     [docker_container_manager.py:192] [default-cluster] Starting managed Redis instance in Docker
20-10-10:11:23:13 WARNING  [decorators.py:34] 404 Client Error: Not Found ("network clipper_network not found"), Retrying in 3 seconds...
20-10-10:11:23:16 WARNING  [decorators.py:34] 409 Client Error: Conflict ("Conflict. The container name "/redis-19069" is already in use by container "14dd82e6ea47c707422beeb996315c4466f79f722ebc32813a782660fa0e8c6d". You have to remove (or rename) that container to be able to reuse that name."), Retrying in 6 seconds...
20-10-10:11:23:22 WARNING  [decorators.py:34] 409 Client Error: Conflict ("Conflict. The container name "/redis-19069" is already in use by container "14dd82e6ea47c707422beeb996315c4466f79f722ebc32813a782660fa0e8c6d". You have to remove (or rename) that container to be able to reuse that name."), Retrying in 12 seconds...
20-10-10:11:23:34 WARNING  [decorators.py:34] 409 Client Error: Conflict ("Conflict. The container name "/redis-19069" is already in use by container "14dd82e6ea47c707422beeb996315c4466f79f722ebc32813a782660fa0e8c6d". You have to remove (or rename) that container to be able to reuse that name."), Retrying in 24 seconds...
Traceback (most recent call last):
  File "/home/jiaruifang/miniconda3/envs/torch/lib/python3.6/site-packages/docker/api/client.py", line 259, in _raise_for_status
    response.raise_for_status()
  File "/home/jiaruifang/miniconda3/envs/torch/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.39/containers/create?name=redis-19069

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example_client.py", line 44, in <module>
    clipper_conn.start_clipper()
  File "/data/home/jiaruifang/codes/clipper/clipper_admin/clipper_admin/clipper_admin.py", line 139, in start_clipper
    qf_http_timeout_content, num_frontend_replicas)
  File "/data/home/jiaruifang/codes/clipper/clipper_admin/clipper_admin/docker/docker_container_manager.py", line 208, in start_clipper
    extra_container_kwargs=self.extra_container_kwargs)
  File "/data/home/jiaruifang/codes/clipper/clipper_admin/clipper_admin/decorators.py", line 38, in f_retry
    return f(*args, **kwargs)
  File "/data/home/jiaruifang/codes/clipper/clipper_admin/clipper_admin/docker/docker_api_utils.py", line 65, in run_container
    **extra_container_kwargs)
  File "/home/jiaruifang/miniconda3/envs/torch/lib/python3.6/site-packages/docker/models/containers.py", line 810, in run
    detach=detach, **kwargs)
  File "/home/jiaruifang/miniconda3/envs/torch/lib/python3.6/site-packages/docker/models/containers.py", line 868, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/jiaruifang/miniconda3/envs/torch/lib/python3.6/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/home/jiaruifang/miniconda3/envs/torch/lib/python3.6/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/home/jiaruifang/miniconda3/envs/torch/lib/python3.6/site-packages/docker/api/client.py", line 265, in _result
    self._raise_for_status(response)
  File "/home/jiaruifang/miniconda3/envs/torch/lib/python3.6/site-packages/docker/api/client.py", line 261, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/jiaruifang/miniconda3/envs/torch/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 409 Client Error: Conflict ("Conflict. The container name "/redis-19069" is already in use by container "14dd82e6ea47c707422beeb996315c4466f79f722ebc32813a782660fa0e8c6d". You have to remove (or rename) that container to be able to reuse that name.")
